version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: gafanhoto
      POSTGRES_PASSWORD: gafanhoto@aczg
      POSTGRES_DB: linketinder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: